<img src="https://images.unsplash.com/photo-1628947733273-cdae71c9bfd3?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" width="400" alt="Taxi"><img src="https://www.logo.wine/a/logo/Uber/Uber-Logo.wine.svg" width="400" alt="Uber">

# Partner Business Modeling
***

**Python, Pandas**

*Uber - Model partner economics via expense projections and profit margin analysis.*
***

#### **Assignment**


**Scenario 1:**\
It is going to be a huge Saturday and there will need to be many more cars on the road than last week. In order to get drivers to go online, we're assessing the following two bonus options in terms of cost:

> Option 1: `$50` for each driver that is online at least 8 hours, accepts 90% of requests, completes 10 trips, and has a rating of 4.7 or better during the time frame.\
> Option 2: `$4`/trip for all drivers who complete 12 trips, and have a 4.7 or better rating.

- How much would the total bonus payout be with Option 1?
- How much would the total bonus payout be with Option 2?
- How many drivers would qualify for a bonus under Option 1 but not under Option 2?
- What percentages of drivers online completed less than 10 trips, had an acceptance rate of less than 90%, and had a rating of 4.7 or higher?




**Scenario 2:**\
A taxi driver currently generates `$200` per day in fares (before expenses), works six days a week, takes three weeks off, and has the following expenses:

> Gas - `$200` per week\
> Insurance - `$400` per month\
> Vehicle rent (by the week) - `$500`\
> _The driver doesn't pay gas and rent expenses on off weeks_.

Now, let's assume that the same driver would buy a Town Car and partner with Uber. If he does, his gas expenses would go up by 5%, his insurance expense would decrease by 20%, and he would no longer be renting a vehicle. However, he would need to buy a car. The driver would still take three weeks off per year.

- How much money (after expenses) does the taxi driver make per year without partnering with Uber?
- You are convincing the same driver above to buy a Town Car and partner with Uber. Assuming the new car is `$40,000`, how much would the driver's gross fares need to increase per week to fully pay for the car in year 1 and maintain the same yearly profit margin as before?

----

In [ ]:
import pandas as pd

filepath = 'driver_info.csv'
driver_info = pd.read_csv(filepath)
driver_info.head()

      Name  Trips Completed Accept Rate  Supply Hours  Rating
0    Abdul                1        100%             3     4.8
1  Abraham               12         83%             5     4.7
2  Adelina                1        100%             2     4.7
3   Akilah                1        100%             2     4.9
4     Alec               21         76%            11     5.0

In [ ]:
driver_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119 entries, 0 to 118
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             119 non-null    object
 1   Trips Completed  119 non-null    int64
 2   Accept Rate      119 non-null    object
 3   Supply Hours     119 non-null    int64
 4   Rating           119 non-null    float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.8+ KB

**Accept Rate is a string with a % delimiter, need to convert to a decimal percentage.**

In [ ]:
driver_info['Accept Rate'] = driver_info['Accept Rate'].str.replace('%', '').astype(float)/100
driver_info.head()

      Name  Trips Completed  Accept Rate  Supply Hours  Rating
0    Abdul                1         1.00             3     4.8
1  Abraham               12         0.83             5     4.7
2  Adelina                1         1.00             2     4.7
3   Akilah                1         1.00             2     4.9
4     Alec               21         0.76            11     5.0

**Scenario 1-1: How much would the total bonus payout be with Option 1?**

In [ ]:
option_1_list = driver_info[(driver_info['Supply Hours'] >= 8) & (driver_info['Accept Rate'] >= 0.90) & (driver_info['Rating'] >= 4.7)]
option_1_payout = len(option_1_list) * 50
print('$'+str(option_1_payout))

$1050

**Scenario 1-2: How much would the total bonus payout be with Option 2?**

In [ ]:
option_2_list = driver_info[(driver_info['Trips Completed'] >= 12) & (driver_info['Rating'] >= 4.7)]
option_2_payout = option_2_list['Trips Completed'].sum() * 4
print('$'+str(option_2_payout))

$2976

**Scenario 1-3: How many drivers would qualify for a bonus under Option 1 but not under Option 2?**

In [ ]:
difference = option_1_list[option_1_list['Trips Completed'] < 12]
difference

       Name  Trips Completed  Accept Rate  Supply Hours  Rating
88     Oren               11         0.91             9     4.8
92  Phyllis               10         0.90             8     4.8

**Scenario 1-4: What percentages of drivers online completed less than 10 trips, had an acceptance rate of less than 90%, and had a rating of 4.7 or higher?**

In [ ]:
suboptimal_drivers = len(driver_info[(driver_info['Trips Completed'] < 10) & (driver_info['Accept Rate'] < 0.90) & (driver_info['Rating'] >= 4.7)]) / len(driver_info)
print(str(round(suboptimal_drivers*100,2))+'%')

10.92%

**Scenario 2-1: How much money (after expenses) does the taxi driver make per year without partnering with Uber?**

In [ ]:
work_days = 6
work_weeks = 49
gas = 200 * work_weeks
insurance = 400 * 12
vehicle_rent = 500 * work_weeks

taxi_expenses = gas + insurance + vehicle_rent
taxi_revenue = 200 * work_days * work_weeks
taxi_net_income = taxi_revenue - taxi_expenses
profit_margin = taxi_net_income / taxi_revenue

print('Taxi Revenue: $'+str(taxi_revenue)+' - Taxi Expenses: $'+str(taxi_expenses)+' - Taxi Net Income: $'+str(taxi_net_income)+' - Taxi Profit Margin: '+str(round(profit_margin*100,2))+'%')

Taxi Revenue: $58800 - Taxi Expenses: $39100 - Taxi Net Income: $19700 - Taxi Profit Margin: 33.5%

**Scenario 2-2: You are convincing the same driver above to buy a Town Car and partner with Uber. Assuming the new car is $40,000, how much would the driver's gross fares need to increase per week to fully pay for the car in year 1 and maintain the same yearly profit margin as before?**

In [ ]:
uber_gas = gas * 1.05
uber_insurance = insurance * 0.80
new_car_loan = 40000
uber_expenses = uber_gas + uber_insurance + new_car_loan
new_profit_margin = (taxi_revenue - uber_expenses) / taxi_revenue

print('Profit Margin with the same taxi revenue and new expenses is '+str(round(new_profit_margin*100,2))+'%')

Profit Margin with the same taxi revenue and new expenses is 7.94%

In [ ]:
weekly_fare_increase = taxi_revenue * (profit_margin - new_profit_margin) / work_weeks
print('The driver would have to increase his weekly fare by $'+str(round(weekly_fare_increase,2))+' in order to maintain the same '+str(round(profit_margin*100,2))+'% taxi profit margin and pay off their car loan in one year.')

The driver would have to increase his weekly fare by $306.73 in order to maintain the same 33.5% taxi profit margin and pay off their car loan in one year.